---
title: "Module-5-Assignment"
description: |
  Hypothesis testing and correlation analysis
preview: https://github.com/skywalshUSF/LIS4273_sWalsh_Blog/blob/main/hypotest.png?raw=true
author:
  - name: Skylar Walsh
    url: {}
date: 2025-02-15
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
# Name: Skylar Walsh
# Professor: Lingyao Li
# Course: LIS4273.002
# Date: 2/15/2025

# "Question A"

# The director of manufacturing at a cookies company needs to determine 
# whether a new machine is able to produce a particular type of cookies 
# according to the manufacturer's specifications, which indicate that 
# cookies should have a mean of 70 and standard deviation of 3.5 pounds. 
# A sample of 49 cookies reveals a sample mean breaking strength of 69.1 pounds.

# A1. State the null and alternative hypothesis

# "The null hypothesis (H0) would be that the breaking strength of the cookies
# is equal to 70 pounds."

# "The alternative hypothesis (Ha) would be that the breaking strength of
# the cookies is not equal to 70 pounds."

# A2. Is there evidence that the machine is not meeting the manufacturer's 
# specifications for average strength? Use a 0.05 level of significance

# Here are the sample statistics we are dealing with
sSize <- 49
sMean <- 69.1
pStdDev <- 3.5

# Here is the level of significance that will be used
a <- 0.05

# Here is the population mean
mu <- 70

# Calculate the z-score
z <- (sMean - mu) / (pStdDev/sqrt(sSize))
z


# A3. Compute the p value and interpret its meaning


# Calculate the p-value. This is a two-tailed test
pVal <- 2 * pnorm(abs(z), lower.tail = FALSE)
pVal

# Make the interpretation
if (pVal < a) {
  cat("Reject H0. There is enough evidence to suggest that the machine 
      is not meeting the manufacturer's specifications
      for the average strength")
} else {
  cat("Fail to reject H0. There is not enough evidence to suggest that
       the machine is not meeting the manufacturer's specifications 
       for the average strength")
}

# A4. What would be your answer in (B) if the standard deviation were 
# specified as 1.75 pounds?

# The population standard deviation is now 1.75
pStdDev <- 1.75

# Calculate the z-score
z <- (sMean - mu) / (pStdDev/sqrt(sSize))
z

# Calculate the p-value. This is a two-tailed test
pVal <- 2 * pnorm(abs(z), lower.tail = FALSE)
pVal

# Make the interpretation
if (pVal < a) {
  cat("Reject H0. There is enough evidence to suggest that the machine 
      is not meeting the manufacturer's specifications
      for the average strength")
} else {
  cat("Fail to reject H0. There is not enough evidence to suggest that
       the machine is not meeting the manufacturer's specifications 
       for the average strength")
}


# A5. What would be your answer in (B) if the sample mean were 69 pounds 
# and the standard deviation is 3.5 pounds?

# The sample mean is now 69
sMean <- 69

# The population standard deviation is now 3.5
pStdDev <- 3.5

# Calculate the z-score
z <- (sMean - mu) / (pStdDev/sqrt(sSize))
z

# Calculate the p-value. This is a two-tailed test
pVal <- 2 * pnorm(abs(z), lower.tail = FALSE)
pVal

# Make the interpretation
if (pVal < a) {
  cat("Reject H0. There is enough evidence to suggest that the machine 
      is not meeting the manufacturer's specifications
      for the average strength")
} else {
  cat("Fail to reject H0. There is not enough evidence to suggest that
       the machine is not meeting the manufacturer's specifications 
       for the average strength")
}

# "Question B"

# If xbar = 85, population standard deviation = 8, and n = 64, set up
# 95% confidence interval estimate of the population mean mu.

# List the set of values given
sMean <- 85
pStdDev <- 8
sSize <- 64
conLevel <- 0.95

# Calculate the z-score for the given confidence level
a <- 1 - conLevel
a

# This is a two-tailed test, so alpha will be cut in half
z_crit <- qnorm(1 - a/2)
z_crit

# Solve for e, which stands for the margin of error
e <- z_crit * (pStdDev / sqrt(sSize))
e

# Calculate the upper and lower limit to set up the
# 95% confidence interval

lower_limit <- sMean - e
lower_limit

upper_limit <- sMean + e
upper_limit

# Confidence interval
print("(83.04, 86.96)")

# There is a 95% probability that the population mean would be
# in between these two values


# "Question C"
library(GGally)
# Given the time spent on assignments each week for the sampled 
# girl group and boy group, respectively,

girls_grades <- c(89, 90, 91, 95, 98, 99, 96, 99)
girls_time_spend <- c(19, 20, 22, 25, 28, 30, 32, 36)

boys_grades <- c(86, 84, 92, 93, 93, 96, 98, 98)
boys_time_spend <- c(15, 19, 22, 23, 25, 29, 30, 40)

# Please perform the correlation analysis:

# C1. Calculate the correlation coefficient (Pearson) between time 
# spent and grade for girls' and boys' data sets, respectively.

# Here is the Pearson correlation for the girls
x <- (girls_grades)
y <- (girls_time_spend)
girlsCorr <- data.frame(x, y)
cor(girlsCorr, method = "pearson")

# Here is the Pearson correlation for the boys
x <- (boys_grades)
y <- (boys_time_spend)
boysCorr <- data.frame(x, y)
cor(boysCorr, method = "pearson")

# C2. Use ggpairs to plot the time spent and grade for 
# girls' and boys' datasets, respectively

# Here is the plot to compare the time spent
# and grade for the girls
ggpairs(girlsCorr, upper = list(wrap("cor", size = 5)),
diag = list(continuous = "densityDiag"),)

# Here is the plot to compare the time spent
# and grade for the boys
ggpairs(boysCorr, upper = list(wrap("cor", size = 5)),
diag = list(continuous = "densityDiag"),)
```

