---
title: "Module-9-Assignment"
description: |
  Introduction to tabular data and contingency tables
preview: https://github.com/skywalshUSF/LIS4273_sWalsh_Blog/blob/main/ANOVA.png?raw=true
author:
  - name: Skylar Walsh
    url: {}
date: 2025-03-17
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
# Name: Skylar Walsh
# Professor: Lingyao Li
# Course: LIS4273.002
# Date: 3/17/2025

# 'Question A'

# Your data.frame is listed as below.

# Create the data frame with country, age, salary, and purchased variables
df <- data.frame(
  country = c("France", "Spain", "Germany", "Spain", "Germany", "France", "Spain", "France", "Germany", "France"),
  age = c(44, 27, 30, 38, 40, 35, 52, 48, 45, 37),
  salary = c(6000, 5000, 7000, 4000, 8000, 6000, 5000, 7000, 4000, 8000),
  purchased = c("No", "Yes", "No", "No", "Yes", "Yes", "No", "Yes", "No", "Yes")
)

# A1. Generate a one-way table for "purchased"
tableOne <- table(df$purchased)
tableOne

# The table() function counts the frequency "Yes" and "No"
# appear in the "purchased" column of the data frame.

# The results show that five did not purchase, and
# five did purchase.

# A2. Generate a two-way table for "country" and "purchased."
tableTwo <- table(df$country, df$purchased)
tableTwo

# This is generating a table that will measure the relationship 
# between "country" variables and "purchased" variables

# Ex. In "Germany," two said "No" to purchasing, while one said "Yes."



# 'Question B'

# We will analyze a data frame by creating a contingency table based on the
# number of cylinders and number of gears.

# Generate contingency table also known as rx C table using mtcars dataset. 
data(mtcars)
mtcars_df <- table(mtcars$gear, mtcars$cyl, dnn = c("Gears", "Cylinders"))

# The table counts how many cars in the dataframe have a certain number of
# cylinders and gears.


# B1. Add the addmargins() function to report on the sum totals of 
# the rows and columns of "mtcars_df" table
mtcarsTableMargins <- addmargins(mtcars_df)
mtcarsTableMargins

# The addMargins() function adds row and column sums to the table, helping
# me see the total number of counts.

# What is displayed includes an extra row and column that is labeled "Sum,"
# which indicates the total number of values in a particular row or column.


# B2. Add prop.table() function, and report on the proportional weight 
# of each value in the "mtcars_df" table
mtcarsTableProp <- prop.table(mtcars_df)
mtcarsTableProp

# The prop.table() function converts the table into proportions. This helps
# show the percentage of each category that is compared to the total number
# of observations.














```

