---
title: "Module-7-Assignment"
description: |
  Simple Linear and Multiple Regression Analysis
preview: https://github.com/skywalshUSF/LIS4273_sWalsh_Blog/blob/main/Random-Variable.jpg?raw=true
author:
  - name: Skylar Walsh
    url: {}
date: 2025-02-25
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
# Name: Skylar Walsh
# Professor: Lingyao Li
# Course: LIS4273.002
# Date: 2/25/2025

# 'Question A'

# In this assignment's segment, we will use the following regression equation
# Y = a + bX + e

# -> Y is the value of the dependent variable (Y), what is being 
# predicted or explained

# -> a or Alpha, a constant; equals the value of Y when the value of X=0

# -> b or Beta, the coefficient of X; the slope of the regression line; 
# how much Y changes for each one-unit change in X.

# -> X is the value of the Independent variable (X), what is predicting 
# or explaining the value of Y

# -> e is the error term; the error in predicting the value of Y, given 
# the value of X (it is not displayed in most regression equations).

# The data in this assignment:

x <- c(16, 17, 13, 18, 12, 14, 19, 11, 11, 10)
y <- c(63, 81, 56, 91, 47, 57, 76, 72, 62, 48)


# A1. Define the relationship model between the independent and
# the dependent variable.

# Define the relationship model by creating a linear model
relModel <- lm(y ~ x)

# Print a summary of the regression model
summary(relModel)



# A2. Calculate the coefficients
coefficients(relModel)

# x represents an independent variable or the predictor

# y represents a dependent variable or the response

# The coefficients calculated from summary(relModel) will display the
# values of b0 (the y-intercept) and b1 (the slope)



# 'Question B'

# The following question is posted by Chi Yau the author of R Tutorial With 
# Bayesian Statistics Using Stan and his blog posting regarding Regression 
# analysis.

# Apply the simple linear regression model (see the above formula) for the 
# data set called "visit" (see below), and estimate the discharge duration 
# if the waiting time since the last eruption has been 80 minutes.

# > head(visit)

# discharge  waiting 
# 1   3.600      79 
# 2   1.800      54 
# 3   3.333      74 
# 4   2.283      62 
# 5   4.533      85 
# 6   2.883      55

visit <- data.frame("discharge" = c(3.600, 1.800, 3.333, 2.283, 4.533, 2.883),
                    "waiting"=c(79, 54, 74, 62, 85, 55))

# Employ the following formula discharge ~ waiting and data=visit)

# B1. Define the relationship model between the predictor 
# and the response variable.

# Model the relationship between the predictor variable x and 
# the response variable y
discharge <- lm(discharge ~ waiting, data=visit)


# B2. Extract the parameters of the estimated regression equation with 
# the coefficients function.
coeff <- coefficients(discharge)
coeff


# B3. Determine the fit of the eruption duration using 
# the estimated regression equation.

# Here is the value for the waiting time since the last eruption, also
# known as x (named waiting).
waiting <- 80

# Use the estimated regression equation
predictedDis <- coeff[1]+coeff[2]*waiting
predictedDis


# 'Question C. Multiple Regression'

# We will use a very famous datasets in R called mtcars. This dateset 
# was extracted from the 1974 Motor Trend US magazine, and comprises 
# fuel consumption and 10 aspects of automobile design and performance 
# for 32 automobiles (1973--74 models).

# This data frame contain 32 observations on 11 (numeric) variables.

# [, 1]	mpg	Miles/(US) gallon
# [, 2]	cyl	Number of cylinders
# [, 3]	disp	Displacement (cu.in.)
# [, 4]	hp	Gross horsepower
# [, 5]	drat	Rear axle ratio
# [, 6]	wt	Weight (1000 lbs)
# [, 7]	qsec	1/4 mile time
# [, 8]	vs	Engine (0 = V-shaped, 1 = straight)
# [, 9]	am	Transmission (0 = automatic, 1 = manual)
# [,10]	gear	Number of forward gears

# To call mtcars data in R
# R comes with several built-in data sets, which are generally used as 
# demo data for playing with R functions. One of those datasets build 
# in R is mtcars. In this question, we will use 4 of the variables found 
# in mtcars by using the following function

#input <- mtcars[,c("mpg","disp","hp","wt")]
#print(head(input))

# C1. Examine the relationship Multi Regression Model as stated above 
# and its Coefficients using 4 different variables 
# from mtcars (mpg, disp, hp and wt). Report on the result and explanation 
# what does the multi regression model and coefficients tell about the data. 

# Claim the mtcars dataset by loading it
data(mtcars)

# Select the variables that are of importance
input <- mtcars[,c("mpg", "disp", "hp", "wt")]

# Apply the multiple linear regression equation
multModel <- lm(formula = mpg ~ disp + hp + wt, data = input)

# Print a summary of the regression model
summary(multModel)

# Calculate the coefficients
coefficients(multModel)

# The main objective of the multiple regression model that was used is to
# analyze the relationship between the fuel efficiency (variable mpg)
# and the three independent variables: disp for displacement, hp 
# for horse power, and wt for weight. Using the data set called mtcars,
# I was able to create a multiple regression model to estimate the
# mpg based on the three variables. According to the output from the multModel
# variable, wt is the strongest predictor for fuel efficiency. In summary, as 
# the weight gets larger, the miles per gallon gets smaller. Also, as the miles
# per gallon increases, the weight decreases. With this in mind, every
# predictor variable affects the miles per gallon differently.




```

